### ISSUE TITLE
publish jars to maven central

### ISSUE THREAD

**Issue by spencergibb** [Ecwid/consul-api#8]
We're starting to use this great library in [spring-cloud-consul](https://github.com/spring-cloud/spring-cloud-consul).  Before we could go GA, we would need these to be in maven central.

**Comment by chrismiller** [comment]
Related to this, the current Maven pom file on nexus.ecwid.com (URL below) doesn't include consul-api's dependencies on httpclient, gson and hamcrest-core. This makes it difficult to use because the dependencies have to be managed manually by the user.

http://nexus.ecwid.com/content/groups/public/com/ecwid/consul/consul-api/1.1.0/consul-api-1.1.0.pom

**Comment by vgv** [comment]
Hi, guys

I've passed the initial procedure of releasing JARs into Maven Central. 
I've uploaded the latest version of consul-api into Central:  com.ecwid.consul:consul-api:1.1.2

**Comment by spencergibb** [comment]
@vgv :+1: thanks a ton!
